[window]
opacity = 1.0
title = "Alacritty - Night Owl"

[font]
normal.family = "MesloLGS NF"
normal.style = "Italic"
size = 12.0

[colors.primary]
background = "#010116"
foreground = "#D6D6DE"

[colors.cursor]
text = "#010116"
cursor = "#D6D6DE"

[colors.normal]
black   = "#010116"
red     = "#EF5350"
green   = "#22DA6E"
yellow  = "#ADDB67"
blue    = "#82AAFF"
magenta = "#C792EA"
cyan    = "#21C7A8"
white   = "#FFFFFF"

[colors.bright]
black   = "#575656"
red     = "#EF5350"
green   = "#22DA6E"
yellow  = "#FFEB95"
blue    = "#82AAFF"
magenta = "#C792EA"
cyan    = "#7FDBCA"
white   = "#FFFFFF"